// <auto-generated />
namespace UTS_PLOO_151524025_Reka_Alamsyah.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RelationShipProductCategorySupp1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RelationShipProductCategorySupp1));
        
        string IMigrationMetadata.Id
        {
            get { return "201804120355027_RelationShipProductCategorySupp1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
